docs:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - README.md
        - release-notes.md
        - DEVELOPMENT.md
        - ONBOARDING.md
        - docs/**

internal:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - .github/**
        - .vscode/**
        - scripts/**
        - .gitignore
        - .pre-commit-config.yaml
      - all-globs-to-all-files:
        - '!pyproject.toml'

# テスト関連の変更
tests:
  - all:
    - changed-files:
      - any-glob-to-any-file:
        - tests/**
        - conftest.py
        - pytest.ini